---
name: Build Kernel Packages
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

# yamllint disable rule:line-length
# yamllint disable-line rule:truthy
on:
  push:
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force kernel build and release'
        required: true
        type: boolean
      use_local_patches:
        description: 'Override patchset with local patches'
        required: true
        type: boolean
      patch_release_version:
        description: 'Local patch release version'
        required: false
        type: number

  schedule:
    - cron: '0 06 * * *'

jobs:
  extract_params:
    name: Extract Parameters
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.verify.outputs.should_build }}
      release_tag: ${{ steps.verify.outputs.release_tag }}
    steps:
      - name: Fetch build parameters
        id: fetch
        run: |
          echo "#### Step: $GITHUB_ACTION" >> $GITHUB_STEP_SUMMARY
          echo "inputs.force_build: ${{ inputs.force_build }}" >> $GITHUB_STEP_SUMMARY
          echo "inputs.use_local_patches: ${{ inputs.use_local_patches }}" >> $GITHUB_STEP_SUMMARY
          echo "inputs.patch_release_version: ${{ inputs.patch_release_version }}" >> $GITHUB_STEP_SUMMARY

          git clone --depth 1 https://github.com/t2linux/T2-Ubuntu-Kernel.git
          grep '^KERNEL_VERSION=' T2-Ubuntu-Kernel/build.sh | head -n 1 > build_params
          if [ -n "${{ inputs.patch_release_version }}" ]; then
            echo "PKGREL=${{ inputs.patch_release_version }}" >> build_params
          else
            grep '^PKGREL=' T2-Ubuntu-Kernel/build.sh | head -n 1 >> build_params
          fi

          grep '^T2_PATCHES_GIT_URL=' T2-Ubuntu-Kernel/patch_driver.sh | head -n 1 >> build_params
          grep '^T2_PATCHES_BRANCH_NAME=' T2-Ubuntu-Kernel/patch_driver.sh | head -n 1 >> build_params

          T2_PATCHES_COMMIT_HASH=$(grep '^T2_PATCHES_COMMIT_HASH=' T2-Ubuntu-Kernel/patch_driver.sh | head -n 1 | cut -d'=' -f2)
          if [ "${T2_PATCHES_COMMIT_HASH}" = "HEAD" ]; then
            source build_params
            git clone --single-branch --branch ${T2_PATCHES_BRANCH_NAME} ${T2_PATCHES_GIT_URL} patches
            T2_PATCHES_COMMIT_HASH=$(git -C patches rev-parse HEAD)
          fi
          echo T2_PATCHES_COMMIT_HASH=${T2_PATCHES_COMMIT_HASH} >> build_params

          #grep '^APPLE_BCE_REPOSITORY=' T2-Ubuntu-Kernel/build.sh | head -n 1 >> build_params
          source build_params
          #git clone --depth 1 "${APPLE_BCE_REPOSITORY}" apple-bce
          #echo APPLE_BCE_COMMIT_HASH=$(git -C apple-bce rev-parse HEAD)  >> build_params

          #APPLE_GMUX_T2_REPOSITORY="https://github.com/Redecorating/apple-gmux-t2.git"
          #echo APPLE_GMUX_T2_REPOSITORY=${APPLE_GMUX_T2_REPOSITORY} >> build_params
          #git clone --depth 1 $APPLE_GMUX_T2_REPOSITORY
          #echo APPLE_GMUX_T2_COMMIT_HASH=$(git -C apple-gmux-t2 rev-parse HEAD) >> build_params

          echo "patch_sha=$(sha256sum T2-Ubuntu-Kernel/patches/*.patch | sha256sum | cut -d' ' -f 1)" >> build_params

          echo "Build parameters: " >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat build_params >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Store build params
        uses: actions/upload-artifact@v4
        with:
          name: build-params
          path: |
            build_params
            T2-Ubuntu-Kernel/patches/*.patch

      - name: Verify if the build should be made
        id: verify
        run: |
          echo "#### Step: $GITHUB_ACTION" >> $GITHUB_STEP_SUMMARY
          curl -L --silent https://github.com/andersfugmann/T2-Debian-Kernel/releases/latest/download/build_params > prev_build_params || true

          SHOULD_BUILD=true
          if diff -q build_params prev_build_params > /dev/null; then
            SHOULD_BUILD=false
          fi

          source ./build_params
          echo "should_build=${SHOULD_BUILD}" >> $GITHUB_OUTPUT
          echo "release_tag=${KERNEL_VERSION}-${PKGREL}" >> $GITHUB_OUTPUT

          echo 'Output parameters' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat $GITHUB_OUTPUT >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  debian_kernel_config:
    name: Extract debian kernel config
    needs: extract_params
    if: needs.extract_params.outputs.should_build == 'true' || inputs.force_build
    runs-on: ubuntu-latest
    steps:
      - name: Copy Debian Kernel config
        id: copy_debian_kernel_config
        run: |
          echo "#### Step: $GITHUB_ACTION" >> $GITHUB_STEP_SUMMARY
          cat <<EOF > build.sh
          #!/bin/bash -ex
            echo "deb http://ftp.debian.org/debian/ experimental main non-free non-free-firmware contrib" >> /etc/apt/sources.list.d/experimental.list
            apt -q update
            apt -q install -t experimental -y linux-image-amd64
            CONFIG=\$(ls /boot/config-*-amd64 | sort | tail -n 1)
            cp -v \${CONFIG} /workspace/debian_kernel_config
          EOF

          echo "#### script:" >> $GITHUB_STEP_SUMMARY
          echo '```sh' >> $GITHUB_STEP_SUMMARY
          cat build.sh >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

          chmod +x build.sh
          docker pull debian:unstable
          docker run -t -v "$(pwd):/workspace" debian:unstable /bin/bash -c /workspace/build.sh

      - name: Upload kernel config
        uses: actions/upload-artifact@v4
        with:
          name: debian-kernel-config
          path: |
            debian_kernel_config

  build:
    name: Build kernel
    needs: [extract_params, debian_kernel_config]
    runs-on: ubuntu-latest

    steps:
      - name: Get Build Parameters
        uses: actions/download-artifact@v4
        with:
          name: build-params

      - name: Setup Environment
        id: setup_environment
        run: |
          source ./build_params
          cat ./build_params >> $GITHUB_ENV
          echo "KERNEL_PATH=${GITHUB_WORKSPACE}/linux-${KERNEL_VERSION}" >> $GITHUB_ENV
          echo "### Build kernel: ${KERNEL_VERSION}" >> $GITHUB_STEP_SUMMARY

      - name: Get Kernel
        run: |
          curl --silent https://mirrors.edge.kernel.org/pub/linux/kernel/v${KERNEL_VERSION%%.*}.x/linux-${KERNEL_VERSION}.tar.xz | tar -Jx

      - name: Get repositories
        run: |
          git clone --single-branch --branch ${T2_PATCHES_BRANCH_NAME} ${T2_PATCHES_GIT_URL} patches
          git -C patches checkout ${T2_PATCHES_COMMIT_HASH}

          if [ "${{ inputs.use_local_patches }}" = "true" ]; then
            git clone https://github.com/andersfugmann/T2-Debian-Kernel.git local_patches
          fi


      - name: Patch kernel
        id: patch_kernel
        run: |
          echo "#### Step: $GITHUB_ACTION" >> $GITHUB_STEP_SUMMARY
          cp -v T2-Ubuntu-Kernel/patches/*.patch patches 2>/dev/null || true
          if [ "${{ inputs.use_local_patches }}" = "true" ]; then
            cp -v local_patches/patches/*.patch patches 2>/dev/null || true
          fi
          ## Remove empty patches
          for f in patches/*patch; do
            echo "Patch: $f" >> $GITHUB_STEP_SUMMARY
            [ -s $f ] || (echo "remove empty patch $f" >> $GITHUB_STEP_SUMMARY; rm -f $f)
          done

          cd ${KERNEL_PATH}
          echo "Applying patches" | tee -a $GITHUB_STEP_SUMMARY
          while read -r file; do
            echo " * $(basename $file)" | tee -a $GITHUB_STEP_SUMMARY
            (patch -p1 --dry-run < "$file" && patch -p1 < "$file") || echo "Failed to apply patch: $f" >> $GITHUB_STEP_SUMMARY
          done < <(find "${GITHUB_WORKSPACE}/patches" -type f -name "*.patch" | sort)


      - name: Get Debian kernel config
        uses: actions/download-artifact@v4
        with:
          name: debian-kernel-config

      - name: Update Kernel Config
        id: update_kernel_config
        run: |
          cp debian_kernel_config ${KERNEL_PATH}/.config

          cd ${KERNEL_PATH}
          ./scripts/config --module CONFIG_BT_HCIBCM4377
          ./scripts/config --module CONFIG_APPLE_BCE
          ./scripts/config --module CONFIG_HID_APPLETB_BL
          ./scripts/config --module CONFIG_HID_APPLETB_KBD
          ./scripts/config --module CONFIG_DRM_APPLETBDRM

          ./scripts/config --module CONFIG_HID_APPLE_MAGIC_BACKLIGHT


          # Disable built in GMUX
          ./scripts/config --module CONFIG_APPLE_GMUX

          # Required by APPLE_BCE. This should already be set.
          ./scripts/config --enable CONFIG_IRQ_REMAP
          ./scripts/config --module CONFIG_HID_APPLE

          # Only support intel cpu
          ./scripts/config --disable CONFIG_GENERIC_CPU
          ./scripts/config --enable CONFIG_PROCESSOR_SELECT
          ./scripts/config --enable CONFIG_MCORE2
          ./scripts/config --enable CONFIG_CPU_SUP_INTEL
          ./scripts/config --disable CONFIG_X86_AMD_PLATFORM_DEVICE
          ./scripts/config --disable CONFIG_CPU_SUP_AMD
          ./scripts/config --disable CONFIG_CPU_SUP_HYGON
          ./scripts/config --disable CONFIG_CPU_SUP_CENTAUR
          ./scripts/config --disable CONFIG_CPU_SUP_ZHAOXIN
          ./scripts/config --disable CONFIG_X86_MCE_AMD
          ./scripts/config --disable CONFIG_PERF_EVENTS_AMD_POWER
          ./scripts/config --disable CONFIG_PERF_EVENTS_AMD_UNCORE
          ./scripts/config --disable CONFIG_MICROCODE_AMD
          ./scripts/config --disable CONFIG_AMD_MEM_ENCRYPT

          # Generic changes to mimic ubuntu
          ./scripts/config --disable CONFIG_GENERIC_IRQ_INJECTION
          ./scripts/config --disable CONFIG_CONTEXT_TRACKING_USER
          ./scripts/config --enable CONFIG_IRQ_SIM
          ./scripts/config --disable CONFIG_NO_HZ_FULL
          ./scripts/config --enable CONFIG_NO_HZ_IDLE
          ./scripts/config --enable CONFIG_NO_HZ
          ./scripts/config --disable CONFIG_CONTEXT_TRACKING_USER
          ./scripts/config --enable CONFIG_USERMODE_DRIVER
          ./scripts/config --enable CONFIG_SCHED_CORE
          ./scripts/config --enable CONFIG_UCLAMP_TASK
          ./scripts/config --set-val CONFIG_UCLAMP_BUCKETS_COUNT 5
          ./scripts/config --enable CONFIG_UCLAMP_TASK_GROUP
          ./scripts/config --enable CONFIG_BOOT_CONFIG
          ./scripts/config --enable CONFIG_X86_EXTENDED_PLATFORM
          ./scripts/config --enable CONFIG_X86_NUMACHIP
          ./scripts/config --enable CONFIG_X86_UV
          ./scripts/config --enable CONFIG_GART_IOMMU
          ./scripts/config --enable CONFIG_X86_MCELOG_LEGACY
          ./scripts/config --enable CONFIG_ARCH_MEMORY_PROBE
          ./scripts/config --enable CONFIG_X86_PMEM_LEGACY
          ./scripts/config --enable CONFIG_X86_CHECK_BIOS_CORRUPTION
          ./scripts/config --enable CONFIG_X86_BOOTPARAM_MEMORY_CORRUPTION_CHECK
          ./scripts/config --enable CONFIG_CPU_UNRET_ENTRY
          ./scripts/config --enable CONFIG_CPU_SRSO
          ./scripts/config --enable CONFIG_PM_WAKELOCKS
          ./scripts/config --enable CONFIG_PCIE_EDR
          ./scripts/config --set-val CONFIG_PM_WAKELOCKS_LIMIT 100
          ./scripts/config --enable CONFIG_PM_WAKELOCKS_GC
          ./scripts/config --enable CONFIG_WQ_POWER_EFFICIENT_DEFAULT
          ./scripts/config --module CONFIG_ACPI_AC
          ./scripts/config --module CONFIG_ACPI_BATTERY
          ./scripts/config --module CONFIG_ACPI_BUTTON
          ./scripts/config --enable CONFIG_ACPI_DPTF
          ./scripts/config --module CONFIG_DPTF_POWER
          ./scripts/config --module CONFIG_DPTF_PCH_FIVR
          ./scripts/config --enable CONFIG_TPS68470_PMIC_OPREGION
          ./scripts/config --enable CONFIG_ACPI_VIOT
          ./scripts/config --enable CONFIG_CPU_IDLE_GOV_TEO
          ./scripts/config --enable CONFIG_TRANSPARENT_HUGEPAGE_MADVISE
          ./scripts/config --disable CONFIG_TRANSPARENT_HUGEPAGE_ALWAYS
          ./scripts/config --enable CONFIG_PAGE_IDLE_FLAG
          ./scripts/config --enable CONFIG_IDLE_PAGE_TRACKING
          ./scripts/config --enable CONFIG_DEVICE_PRIVATE
          ./scripts/config --enable CONFIG_SOC_BUS
          ./scripts/config --enable CONFIG_REGMAP_SPI
          ./scripts/config --enable CONFIG_EFI_RCI2_TABLE
          ./scripts/config --enable CONFIG_EFI_COCO_SECRET
          ./scripts/config --module CONFIG_THUNDER_NIC_PF
          ./scripts/config --module CONFIG_THUNDER_NIC_VF
          ./scripts/config --module CONFIG_THUNDER_NIC_BGX
          ./scripts/config --module CONFIG_THUNDER_NIC_RGX
          ./scripts/config --set-val CONFIG_MODULE_SIG n
          ./scripts/config --set-val CONFIG_MODULE_SIG_ALL n

          # Remove debug info
          ./scripts/config --disable CONFIG_DEBUG_INFO_BTF_MODULES
          ./scripts/config --disable CONFIG_DEBUG_INFO_BTF
          ./scripts/config --disable CONFIG_DEBUG_INFO_COMPRESSED_NONE
          ./scripts/config --disable CONFIG_DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT
          ./scripts/config --disable CONFIG_DEBUG_INFO
          ./scripts/config --disable CONFIG_DEBUG_LIST
          ./scripts/config --disable CONFIG_DEBUG_MEMORY_INIT
          ./scripts/config --enable CONFIG_DEBUG_INFO_NONE

          cp .config ../t2_kernel_config

      - name: Upload kernel config
        uses: actions/upload-artifact@v4
        with:
          name: t2-kernel-config
          path: |
            t2_kernel_config

      - name: Free up disk space
        id: free_space
        #if: false
        run: |
          echo "#### Step: $GITHUB_ACTION" >> $GITHUB_STEP_SUMMARY

          echo 'Before: ' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          df -h >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

          sudo apt -q remove dotnet\* php\* mono\* aspnet\* clang\* java\* ant openjdk\* -y
          sudo apt -q autopurge -y
          sudo rm -fr /usr/local/lib/android

          echo 'After: ' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          df -h >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Build Kernel
        id: build_kernel
        env:
          DOCKER_IMAGE: debian:unstable
          DEBIAN_PACKAGES: >
            build-essential debhelper
            bc rsync kmod cpio bison flex libelf-dev libssl-dev pahole
            python3-minimal ca-certificates dh-exec openssl
            libncurses5-dev dwarves python3 zstd

        run: |
          echo "#### Step: $GITHUB_ACTION" >> $GITHUB_STEP_SUMMARY
          cat <<EOF > build.sh
          #!/bin/bash -ex
          apt -q update
          apt -q install -y ${DEBIAN_PACKAGES}
          apt -q autoclean

          make -C /workspace/linux-${KERNEL_VERSION} olddefconfig

          make -C /workspace/linux-${KERNEL_VERSION} bindeb-pkg \
            -j $(( $(getconf _NPROCESSORS_ONLN) + 1 )) \
            LOCALVERSION=-t2 KDEB_PKGVERSION=${KERNEL_VERSION}-${PKGREL}
          EOF

          echo '```sh' >> $GITHUB_STEP_SUMMARY
          cat build.sh >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

          chmod +x build.sh
          docker pull ${DOCKER_IMAGE}
          docker run -t -v "$(pwd):/workspace" ${DOCKER_IMAGE} /bin/bash -c /workspace/build.sh
          res=$?
          ls -l ${KERNEL_PATH}/certs
          exit $res

      - name: Prepare Release
        run: |
          cp ${KERNEL_PATH}/.config kernel_config_${KERNEL_VERSION}
          sudo rm -fr linux-${KERNEL_VERSION}
          sudo rm -f linux-image-*-dbg_*.deb
          sha256sum *deb > sha256

      - name: Store Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build_artifacts
          path: |
            kernel_config_*
            build_params
            *.deb
            sha256

  release:
    name: Create Release
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [extract_params, build]
    steps:
      - name: Get Build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build_artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kernel_config_*
            *.deb
            build_params
            sha256

          tag_name: v${{ needs.extract_params.outputs.release_tag }}
          draft: false
          body: >
            Installation instructions are given
            [here](https://github.com/andersfugmann/T2-Debian-Kernel#installation).
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cleanup_releases:
    name: Cleanup old releases
    needs: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Nats-ji/delete-old-releases@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        keep-count: 3
        keep-old-minor-releases: true
        keep-old-minor-releases-count: 1
        remove-tags: true
        dry-run: false

  skip_build:
    name: Skip build
    needs: extract_params
    if: needs.extract_params.outputs.should_build == 'false' && inputs.force_build == false
    runs-on: ubuntu-latest
    steps:
      - name: Build skipped
        run: |
          echo "Skippping build - already released"
